djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("student/", include("student.urls")),
    path("member/", include("member.urls")),
    path("member/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]

main/urls.py
from main import views as user_views
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.home, name="home"),
    path('profile/', user_views.profile, name='profile'),
]

student/urls.py
import django.views.generic
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from . import views
from .views import student_profile, student_dashboard, exam_list, exam_create

app_name = "student"
urlpatterns = [
    path("", views.home, name="home"),
    path("student_profile/", student_profile, name="student_profile"),
    path("student_dashboard/", student_dashboard, name="student_dashboard"),
    path('exam_create/<str:pk_exam>', exam_create, name='exam_create'),
    # path("exam_list", login_required(TemplateView.as_view)),
    path("exam_list", exam_list.as_view(), name='exam_list'),
]

student/models.py
from django.db import models

# Choices used for model Student
from django.db.models import ManyToManyField

from member.models import Member

EXAM_SELECTION = [
    ('', ''),
    ('HO-AM', 'HO-AM'),
    ('Seed Form', 'Seed Form'),
    ('Plant Form', 'Plant Form'),
    ('Water Form', 'Water Form'),
    ('Sun Form', 'Sun Form'),
    ('Earth Form', 'Earth Form'),
    ('Fire Form', 'Fire Form'),
    ('Sky Form', 'Sky Form'),
    ('Tiger Form', 'Tiger Form'),
    ('Oak Form', 'Oak Form'),
    ('Eagle Form', 'Eagle Form'),
    ('Ocean Form', 'Ocean Form'),
    ('River Form', 'River Form'),
    ('Bear Form', 'Bear Form'),
    ('Mountain Form', 'Mountain Form')
]

RANK_CHOICES = [
    ('BLANK', 'N/A'),
    ('CUB_WHITE', 'Cub_White'),
    ('CUB_YELLOW', 'Cub_Yellow'),
    ('CUB_GREEN', 'Cub_Green'),
    ('CUB_BLUE', 'Cub_Blue'),
    ('CUB_BROWN', 'Cub_Brown'),
    ('CUB_RED', 'Cub_Red'),
    ('CUB_BLACK', 'Cub_Black'),
    ('CUB_GRADUATE', 'Cub_Graduate'),
    ('WHITE', 'White'),
    ('YELLOW', 'Yellow'),
    ('GREEN_1', 'Green_1'),
    ('GREEN_2', 'Green_2'),
    ('GREEN_3', 'Green_3'),
    ('BLUE_1', 'Blue_1'),
    ('BLUE_2', 'Blue_2'),
    ('BLUE_3', 'Blue_3'),
    ('BROWN_1', 'Brown_1'),
    ('BROWN_2', 'Brown_2'),
    ('BROWN', 'Brown_3'),
    ('RED_1', 'Red_1'),
    ('RED_2', 'Red_2'),
    ('RED_3', 'Red_3'),
    ('PROBATIONARY_BLACK', 'Probationary_Black'),
    ('PROBATIONARY_BLACK_1ST', 'Probationary_Black_1ST'),
    ('PROBATIONARY_BLACK_2ND', 'Probationary_Black_2ND'),
    ('PROBATIONARY_BLACK_3RD', 'Probationary_Black_3RD'),
    ('PROBATIONARY_BLACK_4TH', 'Probationary_Black_4TH'),
    ('BLACK_1ST_L1', 'Black_1ST_L1'),
    ('BLACK_1ST_L2', 'Black_1ST_L2'),
    ('BLACK_1ST_L3', 'Black_1ST_L3'),
    ('BLACK_1ST_L4', 'Black_1ST_L4'),
    ('BLACK_2ND_L1', 'Black_2ND_L1'),
    ('BLACK_2ND_L2', 'Black_2ND_L2'),
    ('BLACK_2ND_L3', 'Black_2ND_L3'),
    ('BLACK_2ND_L4', 'Black_2ND_L4'),
    ('BLACK_3RD_L1', 'Black_3RD_L1'),
    ('BLACK_3RD_L2', 'Black_3RD_L2'),
    ('BLACK_3RD_L3', 'Black_3RD_L3'),
    ('BLACK_3RD_L4', 'Black_3RD_L4'),
    ('BLACK_4TH_L1', 'Black_4TH_L1'),
    ('BLACK_4TH_L2', 'Black_4TH_L2'),
    ('BLACK_4TH_L3', 'Black_4TH_L3'),
    ('SR_1ST_DEGREE', 'Sr_1st_Degree'),
    ('SR_2ND_DEGREE', 'Sr_2nd_Degree'),
    ('SR_3RD_DEGREE', 'Sr_3rd_Degree'),
    ('SR_4TH_DEGREE', 'Sr_4th_Degree')
]

TKD_CHOICES = [
    ('BLANK', 'N/A'),
    ('TIGER CUB', 'Tiger Cub'),
    ('JR', 'Jr'), ('YOUTH', 'Youth'),
    ('ADULT', 'Adult')
]

XP_CHOICES = [
    ('BLANK', 'N/A'),
    ('BEGINNER', 'Beginner'),
    ('INTERMEDIATE', 'Intermediate'),
    ('ADVANCED', 'Advanced')
]

SC_CHOICES = [
    ('BLANK', 'N/A'),
    ('WHITE', 'White'),
    ('YELLOW', 'Yellow')
]

INSRTUCTOR_CHOICES = [
    ('BLANK', 'N/A'),
    ('LEADERSHIP', 'Leadership'),
    ('ASSISTANT', 'Assistant'),
    ('HONORS', 'Honors'),
]


# Create your models here.
class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    age = models.CharField(max_length=3)
    rank = models.CharField(max_length=200, choices=RANK_CHOICES)
    tkd_program = models.CharField(max_length=200, choices=TKD_CHOICES)
    xp_program = models.CharField(max_length=100, choices=XP_CHOICES)
    sc_program = models.CharField(max_length=100, choices=SC_CHOICES)
    instructor = models.BooleanField()
    instructor_level = models.CharField(max_length=100, choices=INSRTUCTOR_CHOICES, default='N/A')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.last_name + ', ' + self.first_name


class Exam(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    exam_title = models.CharField(max_length=20, choices=EXAM_SELECTION, blank=True)
    form_cadence = models.BooleanField(default=False)
    contact = models.BooleanField(default=False)
    one_step = models.BooleanField(default=False)
    sparring = models.BooleanField(default=False)
    ecas = models.BooleanField(default=False)
    boards = models.BooleanField(default=False)
    results = models.CharField(max_length=20, blank=True)
    exam_author = models.CharField(max_length=50, blank=True)
    notes = models.CharField(max_length=250, blank=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (self.exam_title)

student/forms.py
from django import forms

from .models import Exam, Student

EXAM_TIER = [
    ('', ''),
    ('Leveled-White', 'Leveled-White'),
    ('Leveled-Yellow', 'Leveled-Yellow'),
    ('Leveled-Green', 'Leveled-Green'),
    ('Leveled-Blue', 'Leveled-Blue'),
    ('Leveled-Brown', 'Leveled-Brown'),
    ('Leveled-Red', 'Leveled-Red'),
    ('Elevated *', 'Elevated *'),
    ('Elevated **', 'Elevated **'),
    ('Elevated ***', 'Elevated ***')
]


class ExamCreateForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = (
            'exam_title', 'form_cadence', 'contact', 'one_step', 'sparring',
            'ecas', 'boards', 'notes')


class StudentExamCreateForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('first_name',
                  'last_name',
                  'age',
                  'rank',
                  'tkd_program',
                  'xp_program',
                  'sc_program',
                  'instructor')

student/views.py
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from django.http import HttpResponseRedirect
from .forms import ExamCreateForm
from .models import Student, Exam


# Create your views here.
@login_required
def exam_create(request, pk_exam):
    student = Student.objects.get(pk=pk_exam)
    form = ExamCreateForm(request.POST)
    if request.method == 'POST':
        form = ExamCreateForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.exam_author = request.user
            instance.student_id = pk_exam
            test_results = (instance.form_cadence,
                            instance.contact,
                            instance.one_step,
                            instance.sparring,
                            instance.ecas,
                            instance.boards)
            if test_results == True:
                results = 'pass'
                instance.results = results
                test = datetime.date.day
                # split the date at '-' place into list
                # ex: June 08, 2022 - 01:15:59
                print(datetime.date.day)

                if Student.id == Exam.exam_id and datetime.date.day() == datetime.date.day():
                    return HttpResponseRedirect('/student/student_dashboard')

            else:
                results = 'fail'
                instance.results = results
            instance.save()
            return HttpResponseRedirect('/student/student_dashboard')
        else:
            form = ExamCreateForm
    return render(request, 'exam/exam_create.html', {'form'       : form,
                                                     'student'    : student,
                                                     'exam_author': request.user})


def home(request):
    return render(request=request, template_name="student/home.html")


@login_required
def student_profile(request):
    return render(request=request, template_name="student/student_profile.html")


@login_required
def student_dashboard(request):
    students_all = Student.objects.all()
    return render(request, "student/student_dashboard.html", {'students_all': students_all})


class exam_list(LoginRequiredMixin, ListView):
    model = Exam


class StudentCreteView(LoginRequiredMixin, TemplateView):
    queryset = Exam.objects.filter()
    redirect_field_name = '/login'

templates/student/exam_list.html
{% extends 'main/base.html' %}


{% block content %}

    <!--Main layout-->
    <main class="my-5" style="padding-top: 150px" xmlns="http://www.w3.org/1999/html">
        <div class="btn  btn-primary  py-4 border-3 ">
            <h2><strong>Exam Results</strong></h2>
        </div>
        <div class="container" style="padding-left: 120px">
            <!--Section: Content-->
            {% for object in object_list %}
                <section>

                    <!-- Post -->
                    <div class="row" style="background-color:#FAF9F6;">
                        <div class="col-md-10 mb-4">
                            <h5 class="text-center text-md-start">
                                <strong>
                                    {{ object.student.first_name }} {{ object.student.last_name }}
                                </strong>
                            </h5>
                            <p>
                                Examination Results: {{ object.results|upper }}
                            </p>
                            <!--
                            <button type="button" class="btn btn-primary">Details</button>
                            -->
                        </div>
                    </div>

                    <!-- Post -->

                </section>
                <br>
                <br>
                {% empty %}
                <center><strong>Results Found</strong></center>
            {% endfor %}
            <!-- If object_list is empty -->

            <!--Section: Content-->

            <!-- Pagination -->
            <nav class="my-4" aria-label="...">
                <ul class="pagination pagination-circle justify-content-center">
                    <li class="page-item">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
        </div>
    </main>
    <!--Main layout-->

{% endblock content %}

templates/student/home.html
{% extends 'main/base.html' %}

{% block content %}

    {% load crispy_forms_tags %}



{% endblock %}

templates/student/student_dashboard.html
{% extends 'main/base.html' %}

{% block content %}


    {% load crispy_forms_tags %}

    <!-- Banner -->
    <div style="padding-top: 120px">
        <div class="btn  btn-primary  py-4 border-3 ">
            <h2><strong>STUDENT DASHBOARD LIST</strong></h2>
        </div>
        <div class="p-10 bg-surface-secondary">

            <div class="container">
                <div class="card">
                    <div class="card-header">
                    </div>
                    <div class="table-responsive">

                        <table class="table table-hover table-nowrap">
                            <thead class="table-light">
                            <tr>
                                <th scope="col"><strong>Name</strong></th>
                                <th scope="col"><strong>Age</strong></th>
                                <th scope="col"><strong>Rank</strong></th>
                                <th scope="col"><strong>Level</strong></th>
                                <th scope="col"><strong>Instructor</strong></th>
                                <th scope="col"></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% block student %}
                                {% for student in students_all %}
                                    <tr>
                                        <td data-label="Name">
                                            <img alt="..."
                                                 src="https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=3&w=256&h=256&q=80"
                                                 class="avatar avatar-sm rounded-circle me-2">
                                            <a class="text-heading font-semibold" href="#">
                                                {{ student.first_name }} {{ student.last_name }}
                                            </a>
                                        </td>

                                        <td data-label="Age">
                                            <span>{{ student.age }}</span>
                                        </td>
                                        <td data-label="Rank">
                                            <a class="text-current"
                                               href="">{{ student.rank }}</a>
                                        </td>
                                        <td data-label="Level">
                                            <a class="text-current" href="">{{ student.tkd_program }}</a>
                                        </td>
                                        <td data-label="Instructor">
                                            <button type="button" class="btn btn-outline-info btn-sm">
                                            <span
                                                    class="badge text-danger">{{ student.instructor }}</span>
                                            </button>
                                        </td>
                                        <td data-label="Actions">
                                            </button>
                                            <a href="{% url 'student:exam_create' student.id %}">
                                                <div class="btn-group btn-group-vertical">
                                                    <button type="button" class="btn btn-primary">Exams
                                                    </button>
                                                </div>
                                            </a>

                                        </td>

                                        </td>
                                    </tr>
                                {% endfor %}

                            {% endblock %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/student/student_profile.html
{% extends 'main/base.html' %}

{% block content %}


    {% load crispy_forms_tags %}

    <div class="profile">
        <figure>
            <img src="//s3-us-west-2.amazonaws.com/s.cdpn.io/55758/random-user-31.jpg" alt=""/>
        </figure>
        <header>
            <h1>Maria Gonzalez
                <small>Client Happiness Manager</small></h1>
        </header>

        <div class="toggle">
            <input type="checkbox" class="view_details" id="view_details">
            <label for="view_details" title="tap here to view full profile">☰</label>
        </div>
        <main>
            <dl>
                <dt>Full name</dt>
                <dd>Maria Josephina Gonzalez</dd>
                <dt>Date of birth</dt>
                <dd>August 27, 1987</dd>
                <dt>Hometown</dt>
                <dd>Barcelona, Spain</dd>
                <dt>Occupation</dt>
                <dd>Client Happiness Manager</dd>
                <dt>Loves</dt>
                <dd>Skydiving, Tennis, Romantic dinners</dd>
                <dt>Hates</dt>
                <dd>Taxes, bosses instead of leaders</dd>
                <dt>Social</dt>
                <dd>
                    <a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
                </dd>
            </dl>
        </main>

    </div> <!-- end profile -->

    <p style="padding: 20px;">Use this for whatever you like. Have fun with it!</p>

{% endblock %}