djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("student/", include("student.urls")),
    path("member/", include("member.urls")),
    path("member/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]

main/urls.py
from main import views as user_views
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('', views.home, name="home"),
    path('profile/', user_views.profile, name='profile'),
]

member/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'member'
urlpatterns = [
    path('register_user/',
         views.register_user,
         name='register_user'),
    path('login/',
         auth_views.LoginView.as_view(template_name='member/authentication/login.html'),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='member/authentication/logout.html'),
         name='logout'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='member/authentication/password_change.html'),
         name='password_change'),
    path('password_change_done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='member/authentication/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='member/authentication/password_reset.html'),
         name='password_reset'),
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(template_name='member/authentication/password_reset_done.html'),
         name='password_reset_done'),
]

student/urls.py
import django.views.generic
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from . import views
from .views import student_profile, student_dashboard, exam_list, exam_create

app_name = "student"
urlpatterns = [
    path("", views.home, name="home"),
    path("student_profile/", student_profile, name="student_profile"),
    path("student_dashboard/", student_dashboard, name="student_dashboard"),
    path('exam_create/<str:pk_exam>', exam_create, name='exam_create'),
    # path("exam_list", login_required(TemplateView.as_view)),
    path("exam_list", exam_list.as_view(), name='exam_list'),
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile


# Create your forms here.


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class ExtendedAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Enter a username"}
        )
        self.fields["password"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Enter a password"}
        )


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [

        ]

main/views.py
from django.shortcuts import render, redirect


# Create your views here.


def home(request):
    return render(request=request, template_name="main/home.html")


def profile(request):
    pass

templates/main/includes/footer.html
<footer id="footer" class="top-space">

    <div class="footer1">
        <div class="container">
            <div class="row">

                <div class="col-md-3 widget">
                    <h3 class="widget-title">Contact</h3>
                    <div class="widget-body">
                        <p>+234 23 9873237<br>
                            <a href="mailto:#">some.email@somewhere.com</a><br>
                            <br>
                            234 Hidden Pond Road, Ashland City, TN 37015
                        </p>
                    </div>
                </div>

                <div class="col-md-3 widget">
                    <h3 class="widget-title">Follow me</h3>
                    <div class="widget-body">
                        <p class="follow-me-icons">
                            <a href=""><i class="fa fa-twitter fa-2"></i></a>
                            <a href=""><i class="fa fa-dribbble fa-2"></i></a>
                            <a href=""><i class="fa fa-github fa-2"></i></a>
                            <a href=""><i class="fa fa-facebook fa-2"></i></a>
                        </p>
                    </div>
                </div>

                <div class="col-md-6 widget">
                    <h3 class="widget-title">Text widget</h3>
                    <div class="widget-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi, dolores, quibusdam
                            architecto voluptatem amet fugiat nesciunt placeat provident cumque accusamus itaque
                            voluptate modi quidem dolore optio velit hic iusto vero praesentium repellat commodi ad id
                            expedita cupiditate repellendus possimus unde?</p>
                        <p>Eius consequatur nihil quibusdam! Laborum, rerum, quis, inventore ipsa autem repellat
                            provident assumenda labore soluta minima alias temporibus facere distinctio quas adipisci
                            nam sunt explicabo officia tenetur at ea quos doloribus dolorum voluptate reprehenderit
                            architecto sint libero illo et hic.</p>
                    </div>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

    <div class="footer2">
        <div class="container">
            <div class="row">

                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p class="simplenav">
                            <a href="#">Home</a> |
                            <a href="about.html">About</a> |
                            <a href="sidebar-right.html">Sidebar</a> |
                            <a href="contact.html">Contact</a> |
                            <b><a href="signup.html">Sign up</a></b>
                        </p>
                    </div>
                </div>

                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p class="text-right">
                            Copyright &copy; 2014, Your name. Designed by <a href="http://gettemplate.com/"
                                                                             rel="designer">gettemplate</a>
                        </p>
                    </div>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

</footer>

templates/main/includes/header.html
<!-- Header -->
<header id="head">
    <div class="container">
        <div class="row">
            <h1 class="lead">AWESOME, CUSTOMIZABLE, FREE</h1>
            <p class="tagline">PROGRESSUS: free business bootstrap template by <a
                    href="http://www.gettemplate.com/?utm_source=progressus&amp;utm_medium=template&amp;utm_campaign=progressus">GetTemplate</a>
            </p>
            <p><a class="btn btn-default btn-lg" role="button">MORE INFO</a> <a class="btn btn-action btn-lg"
                                                                                role="button">DOWNLOAD NOW</a></p>
        </div>
    </div>
</header>
<!-- /Header -->

templates/main/includes/messages.html
<!--Messages-->

{% for message in messages %}

    <div class="container">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
{% endfor %}

templates/main/includes/navbar.html
<!--Navbar 1-->
{% load static %}
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top headroom">
    <div class="container">
        <div class="navbar-header">
            <!-- Button for smallest screens -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span
                    class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>
            <a class="navbar-brand" href="{% url 'main:home' %}"><img src="{% static 'images/logo.png' %}"
                                                                      alt="Progressus HTML5 template"></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="{% url 'student:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'student:student_dashboard' %}">Student Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'student:exam_list' %}">Exam Results</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'member:logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">{{ user.username|title }}</a>
                    </li>
                {% else %}
                    <li class="active"><a href="{% url 'main:home' %}">Home</a></li>
                    <li><a href="about.html">About</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">More Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="sidebar-left.html">Left Sidebar</a></li>
                            <li class="active"><a href="sidebar-right.html">Right Sidebar</a></li>
                        </ul>
                    </li>
                    <li><a href="contact.html">Contact</a></li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'member:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'member:register_user' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>
<!-- /.navbar -->